"""
Django settings for djangoProject1 project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t3x)#m9owhmx=b^k&*edvn6_*2ldjh5^+8)e^**j=55r+mr=)3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.md.AuthMiddleware'
]

ROOT_URLCONF = 'djangoProject1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = []

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MENU = {
    "ADMIN": [],
    "CUSTOMER": [],
}
PERMISSION = {
    "ADMIN": {},
    "CUSTOMER": {},
}

# cache缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        }
    }
}

# session配置
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # 指定 Django 使用 cache 作为会话存储引擎。
SESSION_CACHE_ALIAS = 'default'  # 指定用于存储会话数据的缓存别名。
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7

# ###################### 自定义配置 ######################
WEB_LOGIN_URL = "/login/"  # 登录页面
WEB_HOME_URL = "/home/"
WEB_WHITE_URL = ['/login/', '/sms_send/']  # 白名单
WEB_SESSION_KEY = "user_data"  # 登录信息

WEB_MENU = {
    'ADMIN': [
        {
            "text": "客户管理",
            "icon": "bi-person-vcard",
            "children": [
                {"text": "级别列表", "url": "/level/", "name": "level"},
                {"text": "客户列表", "url": "/customer/", "name": "customer"}
            ]
        },
        {
            "text": "订单管理",
            "icon": "bi-cart3",
            "children": [
                {"text": "价格策略", "url": "/policy/", "name": "policy"},
                {"text": "交易记录", "url": "/transaction/", "name": "transaction"}
            ]
        }

    ],
    'CUSTOMER': [
        {
            'text': "订单中心",
            'icon': "fa-bed",
            'children': [
                {'text': "订单管理", 'url': "/my_order/", 'name': "my_order"},
                {'text': "我的交易记录", 'url': "/my_transaction/", 'name': "my_transaction"},
            ]
        },
        {
            'text': "个人资料", 'icon': "bi-house", 'url': "/my_space/", 'name': "my_space"
        }

    ],
}

NB_PERMISSION_PUBLIC = {
    "home": {"text": "首页", 'parent': None},
    "logout": {"text": "注销", 'parent': None},
}
NB_PERMISSION = {
    "ADMIN": {
        "level": {"text": "级别列表", "parent": 'home'},
        "level_add": {"text": "新建级别", 'parent': 'level'},
        "level_edit": {"text": "编辑级别", 'parent': 'level'},
        "level_delete": {"text": "删除级别", 'parent': 'level'},

        "customer": {"text": "客户列表", 'parent': 'home'},
        "customer_add": {"text": "新建客户", 'parent': 'customer'},
        "customer_edit": {"text": "编辑客户", 'parent': 'customer'},
        "customer_reset": {"text": "重置密码", 'parent': 'customer'},
        "customer_delete": {"text": "删除客户", 'parent': 'customer'},
        "customer_change": {"text": "交易记录", 'parent': 'customer'},
        "customer_add_change": {"text": "创建交易", 'parent': 'customer'},

        "policy": {"text": "价格策略", 'parent': None},
        "policy_add": {"text": "创建价格策略", 'parent': 'policy'},
        "policy_edit": {"text": "编辑价格策略", 'parent': 'policy'},
        "policy_delete": {"text": "删除价格策略", 'parent': 'policy'},

        "transaction": {"text": "交易记录", 'parent': None}
    },
    "CUSTOMER": {
        "my_order": {"text": "订单管理", 'parent': None},
        "my_order_add": {"text": "提交订单", 'parent': 'my_order'},
        "my_order_cancel": {"text": "撤销订单", 'parent': 'my_order'},
        "my_transaction": {"text": "交易记录", 'parent': None},
        "my_space": {"text": "个人资料", "parent": None}
    }
}

QUEUE_TASK_NAME = "YANG_TASK_QUEUE"

# 第4个位置
# MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_DANDER_TAG = 50
MESSAGE_TAGS = {
    MESSAGE_DANDER_TAG: "danger"
}
try:
    from .local_settings import *
except Exception:
    pass
